### ISSUE TITLE
Unavailable Dependency - rlb

### ISSUE THREAD

**Issue by Isabello** [bradbrown-llc/dizzyhavoc-bridge#1]
This dependency `import { rlb } from '../../../llc/rlb/mod.ts'` is used in many scripts but seems to be only available on your development machine.

**Comment by bradbrown-llc** [comment]
Good catch, I hadn't published that yet. I just did, code is at https://github.com/bradbrown-llc/rlb. I'll work on updating it into a proper deno module and leave this issue up while I do that, but for now the workaround would be importing it from that new repo.

**Comment by Isabello** [comment]
Thank you!

**Comment by bradbrown-llc** [comment]
Updated https://github.com/bradbrown-llc/rlb to be a deno module, added it although it doesn't show on deno.land (https://deno.land/x/rlb). Maybe it takes some time, if it still doesn't show in an hour or two I'll make an issue on https://github.com/denoland/wanted_modules or reach out to them otherwise to see if it's bugged.

**Comment by bradbrown-llc** [comment]
Opened an issue (https://github.com/denoland/wanted_modules/issues/93) and made a discord post on Deno's server to see if that was the best place to open that kind of issue. If nothing seems to be happening for another day or so, I'll probably just create a new repo and rename the module and try again, failures there seem to be rare.

**Comment by bradbrown-llc** [comment]
resolved, could have sworn only branch creation was necessary to get a deno module to update, but now it appears it is release or tag creation. creating a tag and pushing fixed this, and now the module is up
w00t
